default:
  services:
  - name: docker:24-dind
    command: ["--tls=false"]
  interruptible: true
  before_script:
    - echo "Starting pipeline..."
  after_script:
    - echo "Cleaning up..."
  tags:
    - docker
  cache:
    paths:
      - frontend/node_modules/
      - backend/node_modules/
    
variables:
  DOCKER_HOST: "tcp://docker:2375"
  DOCKER_TLS_CERTDIR: ""
  DOCKER_CLIENT_TIMEOUT: "300"
  COMPOSE_HTTP_TIMEOUT: "300"
  
stages:
  - build
  - build_image
  - test
  - verify
  - deploy

build_f:
  stage: build
  image: node:latest
  script:
    - cd frontend
    - npm install
    - npm run build
  artifacts:
    paths:
      - frontend/build/
    expire_in: 1 week

build_b:
  stage: build
  image: node:latest
  script:
    - cd backend
    - npm install

docker_image:
  image: docker:24
  stage: build_image
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    
    - docker build -t $CI_REGISTRY_IMAGE/frontend:$CI_COMMIT_SHORT_SHA ./frontend
    - docker push $CI_REGISTRY_IMAGE/frontend:$CI_COMMIT_SHORT_SHA

    - docker build -t $CI_REGISTRY_IMAGE/backend:$CI_COMMIT_SHORT_SHA ./backend
    - docker push $CI_REGISTRY_IMAGE/backend:$CI_COMMIT_SHORT_SHA 

pull_and_verify:
  image: docker:24
  stage: verify
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - docker pull $CI_REGISTRY_IMAGE/backend:$CI_COMMIT_SHORT_SHA
    - docker image ls
    - docker inspect $CI_REGISTRY_IMAGE/backend:$CI_COMMIT_SHORT_SHA 
    
test_f:
  stage: test
  image: node:latest
  needs:
    - build_f
  dependencies:
    - build_f
  script:
    - cd frontend
    - npm install
    - npm test -- --passWithNoTests

test_b:
  stage: test
  image: node:latest
  needs:
    - build_b
  dependencies:
    - build_b
  script:
    - cd backend
    - npm install
    - echo "backend tests skipped"

deploy:
  stage: deploy
  script:
    - echo "Deploying application..."
    
  environment:
    name: production

  only:
    - main 